image: node:16

pages:
  script:
  - yarn
  - yarn run build
  - mkdir ./public
  - cp --recursive ./website/* ./public/
  - cp sequelize*.js ./public/
  - cp sequelize*.js.map ./public/

  artifacts:
    paths:
    - public

  only:
  - main
